-- Généré par scripts/gen-catalog.py depuis catalog/assets.csv : ne pas éditer à la main.
-- v4 : nom complet des actifs + catalogue intégré. Un actif déjà présent (même symbole normalisé)
-- garde SA catégorie et SON multiplicateur ; seul son nom est complété s'il était vide.
ALTER TABLE instruments ADD COLUMN name TEXT NOT NULL DEFAULT '';
INSERT INTO instruments (symbol, symbol_key, name, asset_class, default_multiplier) VALUES
        ('US500', 'US500', 'S&P 500', 'index', '1'),
        ('NAS100', 'NAS100', 'Nasdaq 100', 'index', '1'),
        ('US30', 'US30', 'Dow Jones 30', 'index', '1'),
        ('GER40', 'GER40', 'DAX 40', 'index', '1'),
        ('FRA40', 'FRA40', 'CAC 40', 'index', '1'),
        ('UK100', 'UK100', 'FTSE 100', 'index', '1'),
        ('JP225', 'JP225', 'Nikkei 225', 'index', '1'),
        ('EU50', 'EU50', 'Euro Stoxx 50', 'index', '1'),
        ('BTCUSD', 'BTCUSD', 'Bitcoin', 'crypto', '1'),
        ('ETHUSD', 'ETHUSD', 'Ethereum', 'crypto', '1'),
        ('XRPUSD', 'XRPUSD', 'XRP', 'crypto', '1'),
        ('BNBUSD', 'BNBUSD', 'BNB', 'crypto', '1'),
        ('SOLUSD', 'SOLUSD', 'Solana', 'crypto', '1'),
        ('DOGEUSD', 'DOGEUSD', 'Dogecoin', 'crypto', '1'),
        ('TRXUSD', 'TRXUSD', 'TRON', 'crypto', '1'),
        ('ADAUSD', 'ADAUSD', 'Cardano', 'crypto', '1'),
        ('HYPEUSD', 'HYPEUSD', 'Hyperliquid', 'crypto', '1'),
        ('LINKUSD', 'LINKUSD', 'Chainlink', 'crypto', '1'),
        ('BCHUSD', 'BCHUSD', 'Bitcoin Cash', 'crypto', '1'),
        ('XLMUSD', 'XLMUSD', 'Stellar', 'crypto', '1'),
        ('AVAXUSD', 'AVAXUSD', 'Avalanche', 'crypto', '1'),
        ('LTCUSD', 'LTCUSD', 'Litecoin', 'crypto', '1'),
        ('SUIUSD', 'SUIUSD', 'Sui', 'crypto', '1'),
        ('HBARUSD', 'HBARUSD', 'Hedera', 'crypto', '1'),
        ('SHIBUSD', 'SHIBUSD', 'Shiba Inu', 'crypto', '1'),
        ('TONUSD', 'TONUSD', 'Toncoin', 'crypto', '1'),
        ('DOTUSD', 'DOTUSD', 'Polkadot', 'crypto', '1'),
        ('XMRUSD', 'XMRUSD', 'Monero', 'crypto', '1'),
        ('UNIUSD', 'UNIUSD', 'Uniswap', 'crypto', '1'),
        ('AAVEUSD', 'AAVEUSD', 'Aave', 'crypto', '1'),
        ('ENAUSD', 'ENAUSD', 'Ethena', 'crypto', '1'),
        ('NEARUSD', 'NEARUSD', 'NEAR Protocol', 'crypto', '1'),
        ('PEPEUSD', 'PEPEUSD', 'Pepe', 'crypto', '1'),
        ('ETCUSD', 'ETCUSD', 'Ethereum Classic', 'crypto', '1'),
        ('ICPUSD', 'ICPUSD', 'Internet Computer', 'crypto', '1'),
        ('APTUSD', 'APTUSD', 'Aptos', 'crypto', '1'),
        ('ONDOUSD', 'ONDOUSD', 'Ondo', 'crypto', '1'),
        ('ARBUSD', 'ARBUSD', 'Arbitrum', 'crypto', '1'),
        ('ALGOUSD', 'ALGOUSD', 'Algorand', 'crypto', '1'),
        ('ATOMUSD', 'ATOMUSD', 'Cosmos', 'crypto', '1'),
        ('POLUSD', 'POLUSD', 'Polygon', 'crypto', '1'),
        ('FILUSD', 'FILUSD', 'Filecoin', 'crypto', '1'),
        ('VETUSD', 'VETUSD', 'VeChain', 'crypto', '1'),
        ('OPUSD', 'OPUSD', 'Optimism', 'crypto', '1'),
        ('INJUSD', 'INJUSD', 'Injective', 'crypto', '1'),
        ('RENDERUSD', 'RENDERUSD', 'Render', 'crypto', '1'),
        ('TAOUSD', 'TAOUSD', 'Bittensor', 'crypto', '1'),
        ('TIAUSD', 'TIAUSD', 'Celestia', 'crypto', '1'),
        ('SEIUSD', 'SEIUSD', 'Sei', 'crypto', '1'),
        ('BONKUSD', 'BONKUSD', 'Bonk', 'crypto', '1'),
        ('WLDUSD', 'WLDUSD', 'Worldcoin', 'crypto', '1'),
        ('FETUSD', 'FETUSD', 'Artificial Superintelligence Alliance', 'crypto', '1'),
        ('JUPUSD', 'JUPUSD', 'Jupiter', 'crypto', '1'),
        ('LDOUSD', 'LDOUSD', 'Lido DAO', 'crypto', '1'),
        ('QNTUSD', 'QNTUSD', 'Quant', 'crypto', '1'),
        ('STXUSD', 'STXUSD', 'Stacks', 'crypto', '1'),
        ('KASUSD', 'KASUSD', 'Kaspa', 'crypto', '1'),
        ('CROUSD', 'CROUSD', 'Cronos', 'crypto', '1'),
        ('ARUSD', 'ARUSD', 'Arweave', 'crypto', '1'),
        ('RUNEUSD', 'RUNEUSD', 'THORChain', 'crypto', '1'),
        ('EURUSD', 'EURUSD', 'Euro / Dollar américain', 'forex', '100000'),
        ('GBPUSD', 'GBPUSD', 'Livre sterling / Dollar américain', 'forex', '100000'),
        ('USDJPY', 'USDJPY', 'Dollar américain / Yen japonais', 'forex', '100000'),
        ('USDCHF', 'USDCHF', 'Dollar américain / Franc suisse', 'forex', '100000'),
        ('USDCAD', 'USDCAD', 'Dollar américain / Dollar canadien', 'forex', '100000'),
        ('AUDUSD', 'AUDUSD', 'Dollar australien / Dollar américain', 'forex', '100000'),
        ('NZDUSD', 'NZDUSD', 'Dollar néo-zélandais / Dollar américain', 'forex', '100000'),
        ('EURGBP', 'EURGBP', 'Euro / Livre sterling', 'forex', '100000'),
        ('EURJPY', 'EURJPY', 'Euro / Yen japonais', 'forex', '100000'),
        ('EURCHF', 'EURCHF', 'Euro / Franc suisse', 'forex', '100000'),
        ('EURAUD', 'EURAUD', 'Euro / Dollar australien', 'forex', '100000'),
        ('EURCAD', 'EURCAD', 'Euro / Dollar canadien', 'forex', '100000'),
        ('EURNZD', 'EURNZD', 'Euro / Dollar néo-zélandais', 'forex', '100000'),
        ('GBPJPY', 'GBPJPY', 'Livre sterling / Yen japonais', 'forex', '100000'),
        ('GBPCHF', 'GBPCHF', 'Livre sterling / Franc suisse', 'forex', '100000'),
        ('GBPAUD', 'GBPAUD', 'Livre sterling / Dollar australien', 'forex', '100000'),
        ('GBPCAD', 'GBPCAD', 'Livre sterling / Dollar canadien', 'forex', '100000'),
        ('GBPNZD', 'GBPNZD', 'Livre sterling / Dollar néo-zélandais', 'forex', '100000'),
        ('AUDJPY', 'AUDJPY', 'Dollar australien / Yen japonais', 'forex', '100000'),
        ('AUDCAD', 'AUDCAD', 'Dollar australien / Dollar canadien', 'forex', '100000'),
        ('AUDCHF', 'AUDCHF', 'Dollar australien / Franc suisse', 'forex', '100000'),
        ('AUDNZD', 'AUDNZD', 'Dollar australien / Dollar néo-zélandais', 'forex', '100000'),
        ('NZDJPY', 'NZDJPY', 'Dollar néo-zélandais / Yen japonais', 'forex', '100000'),
        ('NZDCAD', 'NZDCAD', 'Dollar néo-zélandais / Dollar canadien', 'forex', '100000'),
        ('NZDCHF', 'NZDCHF', 'Dollar néo-zélandais / Franc suisse', 'forex', '100000'),
        ('CADJPY', 'CADJPY', 'Dollar canadien / Yen japonais', 'forex', '100000'),
        ('CADCHF', 'CADCHF', 'Dollar canadien / Franc suisse', 'forex', '100000'),
        ('CHFJPY', 'CHFJPY', 'Franc suisse / Yen japonais', 'forex', '100000'),
        ('XAUUSD', 'XAUUSD', 'Or (once) / Dollar américain', 'commodity', '100'),
        ('XAGUSD', 'XAGUSD', 'Argent (once) / Dollar américain', 'commodity', '5000'),
        ('USOIL', 'USOIL', 'Pétrole WTI', 'commodity', '1000'),
        ('UKOIL', 'UKOIL', 'Pétrole Brent', 'commodity', '1000'),
        ('NATGAS', 'NATGAS', 'Gaz naturel', 'commodity', '10000'),
        ('COPPER', 'COPPER', 'Cuivre', 'commodity', '25000'),
        ('AAPL', 'AAPL', 'Apple', 'stock', '1'),
        ('MSFT', 'MSFT', 'Microsoft', 'stock', '1'),
        ('NVDA', 'NVDA', 'Nvidia', 'stock', '1'),
        ('AMZN', 'AMZN', 'Amazon', 'stock', '1'),
        ('GOOGL', 'GOOGL', 'Alphabet (Google)', 'stock', '1'),
        ('META', 'META', 'Meta Platforms', 'stock', '1'),
        ('TSLA', 'TSLA', 'Tesla', 'stock', '1'),
        ('NFLX', 'NFLX', 'Netflix', 'stock', '1'),
        ('AMD', 'AMD', 'Advanced Micro Devices', 'stock', '1'),
        ('JPM', 'JPM', 'JPMorgan Chase', 'stock', '1'),
        ('COIN', 'COIN', 'Coinbase', 'stock', '1'),
        ('PLTR', 'PLTR', 'Palantir', 'stock', '1')
ON CONFLICT(symbol_key) DO UPDATE SET name = excluded.name WHERE instruments.name = '';
