//! Coach conversations (tables `coach_conversations` and `coach_turns`, migration v13). A turn is text
//! to read plus the log of what was sent: no statistic, score, alert or insight reads these tables. They
//! are kept in backups (whole-database copy), left out of the CSV export (trades only) and never sent to
//! the AI in another conversation: only [`history`] of the same conversation is replayed.

use super::numbers::AllowedNumbers;
use super::tools::TOOLS_VERSION;
use super::{MAX_HISTORY_BYTES, MAX_TURNS};
use crate::error::{CoreError, Result};
use rusqlite::{params, Connection, OptionalExtension};
use serde::Serialize;
use serde_json::Value;

const MAX_TITLE_CHARS: usize = 60;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum TurnStatus {
    Answered,
    Failed,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ConversationSummary {
    pub id: i64,
    pub title: String,
    pub created_at: i64,
    pub updated_at: i64,
    pub turn_count: usize,
    /// Written with another list of tools: readable, but no new question can be asked in it.
    pub read_only: bool,
    /// The question limit or the history limit is reached: a new conversation is needed.
    pub full: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CoachTurn {
    pub id: i64,
    pub conversation_id: i64,
    pub seq: i64,
    pub created_at: i64,
    pub question: String,
    pub status: TurnStatus,
    /// `ai:<code>` translated by the interface; `None` when answered.
    pub error_code: Option<String>,
    /// Text generated by AI, shown as text only.
    pub answer: Option<String>,
    pub provider: String,
    /// The model that answered (or was asked, for a failed turn).
    pub model: String,
    /// What left the computer during this turn (see CLAUDE.md, « Journal local »).
    pub sent: Value,
    /// Numbers of the answer found nowhere in what the AI was given.
    pub unverified: Vec<String>,
    /// Tokens used, as reported by the provider (`inputTokens`, `outputTokens`, `requests`).
    pub usage: Option<Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Conversation {
    #[serde(flatten)]
    pub summary: ConversationSummary,
    pub turns: Vec<CoachTurn>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum NewTurnOutcome {
    /// `transcript`: the API messages this turn added (question, AI content, tool results, final answer),
    /// replayed as they are in the next turns of the same conversation.
    Answered { answer: String, transcript: Vec<Value>, unverified: Vec<String> },
    Failed { error_code: String },
}

#[derive(Debug, Clone, PartialEq)]
pub struct NewTurn {
    pub question: String,
    pub outcome: NewTurnOutcome,
    pub provider: String,
    pub model: String,
    pub sent: Value,
    pub usage: Option<Value>,
}

/// What a new question of an existing conversation starts from.
#[derive(Debug, Clone, Default)]
pub struct ConversationHistory {
    /// The answered turns' transcripts, in order: exactly what was sent and received before.
    pub messages: Vec<Value>,
    pub turn_count: usize,
    /// Serialized size of `messages`.
    pub bytes: usize,
    /// Numbers the AI was given in this conversation (questions, context lines, tool results), never its own.
    pub allowed: AllowedNumbers,
}

/// Title of a new conversation: the start of its first question.
pub fn title_from(question: &str) -> String {
    let flat = question.split_whitespace().collect::<Vec<_>>().join(" ");
    if flat.chars().count() <= MAX_TITLE_CHARS {
        return flat;
    }
    let cut: String = flat.chars().take(MAX_TITLE_CHARS - 1).collect();
    format!("{}…", cut.trim_end())
}

/// Stores a turn; creates the conversation when `conversation_id` is `None`. One transaction.
pub fn add_turn(conn: &Connection, conversation_id: Option<i64>, turn: &NewTurn, now_ms: i64) -> Result<CoachTurn> {
    let question = turn.question.trim();
    if question.is_empty() {
        return Err(CoreError::Invalid("the question is empty".into()));
    }
    let tx = conn.unchecked_transaction()?;
    let id = match conversation_id {
        Some(id) => {
            let found = tx.execute("UPDATE coach_conversations SET updated_at = ?2 WHERE id = ?1", params![id, now_ms])?;
            if found == 0 {
                return Err(CoreError::NotFound(format!("conversation {id}")));
            }
            id
        }
        None => {
            tx.execute(
                "INSERT INTO coach_conversations (title, created_at, updated_at, tools_version) VALUES (?1, ?2, ?2, ?3)",
                params![title_from(question), now_ms, TOOLS_VERSION],
            )?;
            tx.last_insert_rowid()
        }
    };
    let seq: i64 = tx.query_row("SELECT COALESCE(MAX(seq), 0) + 1 FROM coach_turns WHERE conversation_id = ?1", [id], |r| r.get(0))?;
    let json = |v: &Value| v.to_string();
    let (status, error_code, answer, transcript, unverified) = match &turn.outcome {
        NewTurnOutcome::Answered { answer, transcript, unverified } => (
            "answered",
            None,
            Some(answer.trim().to_owned()),
            Some(json(&Value::Array(transcript.clone()))),
            serde_json::to_string(unverified).unwrap_or_else(|_| "[]".into()),
        ),
        NewTurnOutcome::Failed { error_code } => ("failed", Some(error_code.clone()), None, None, "[]".to_owned()),
    };
    if answer.as_deref() == Some("") {
        return Err(CoreError::Invalid("the answer is empty".into()));
    }
    tx.execute(
        "INSERT INTO coach_turns (conversation_id, seq, created_at, question, status, error_code, answer, provider, model, sent, unverified, transcript, usage)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)",
        params![
            id,
            seq,
            now_ms,
            question,
            status,
            error_code,
            answer,
            turn.provider.trim(),
            turn.model.trim(),
            json(&turn.sent),
            unverified,
            transcript,
            turn.usage.as_ref().map(json)
        ],
    )?;
    let turn_id = tx.last_insert_rowid();
    tx.commit()?;
    get_turn(conn, turn_id)
}

/// Most recently used first.
pub fn list_conversations(conn: &Connection) -> Result<Vec<ConversationSummary>> {
    let mut stmt = conn.prepare(&format!("{SUMMARY} GROUP BY c.id ORDER BY c.updated_at DESC, c.id DESC"))?;
    let rows = stmt.query_map([], summary_row)?;
    Ok(rows.collect::<rusqlite::Result<_>>()?)
}

pub fn get_conversation(conn: &Connection, id: i64) -> Result<Conversation> {
    let summary = get_summary(conn, id)?;
    let mut stmt = conn.prepare(&format!("{TURN} WHERE conversation_id = ?1 ORDER BY seq"))?;
    let turns = stmt.query_map([id], turn_row)?.collect::<rusqlite::Result<_>>()?;
    Ok(Conversation { summary, turns })
}

pub fn rename_conversation(conn: &Connection, id: i64, title: &str) -> Result<ConversationSummary> {
    let title = title.split_whitespace().collect::<Vec<_>>().join(" ");
    if title.is_empty() || title.chars().count() > 120 {
        return Err(CoreError::Invalid("the title must have 1 to 120 characters".into()));
    }
    if conn.execute("UPDATE coach_conversations SET title = ?2 WHERE id = ?1", params![id, title])? == 0 {
        return Err(CoreError::NotFound(format!("conversation {id}")));
    }
    get_summary(conn, id)
}

pub fn delete_conversation(conn: &Connection, id: i64) -> Result<()> {
    if conn.execute("DELETE FROM coach_conversations WHERE id = ?1", [id])? == 0 {
        return Err(CoreError::NotFound(format!("conversation {id}")));
    }
    Ok(())
}

/// Deletes every conversation; returns how many there were.
pub fn delete_all_conversations(conn: &Connection) -> Result<usize> {
    Ok(conn.execute("DELETE FROM coach_conversations", [])?)
}

/// The replay of a conversation for its next question. Refuses a conversation written with another
/// list of tools, or one that reached its limits.
pub fn history(conn: &Connection, id: i64) -> Result<ConversationHistory> {
    let summary = get_summary(conn, id)?;
    if summary.read_only {
        return Err(CoreError::Invalid("this conversation was written with another version of the tools: start a new one".into()));
    }
    let mut stmt = conn.prepare("SELECT transcript FROM coach_turns WHERE conversation_id = ?1 AND status = 'answered' ORDER BY seq")?;
    let mut h = ConversationHistory { turn_count: summary.turn_count, ..ConversationHistory::default() };
    for text in stmt.query_map([id], |r| r.get::<_, String>(0))? {
        let text = text?;
        h.bytes += text.len();
        let messages: Vec<Value> = serde_json::from_str(&text).map_err(|e| CoreError::Invalid(format!("stored conversation unreadable: {e}")))?;
        for m in messages {
            add_given(&mut h.allowed, &m);
            h.messages.push(m);
        }
    }
    if summary.full {
        return Err(CoreError::Invalid("this conversation is full: start a new one".into()));
    }
    Ok(h)
}

/// Numbers the AI was given in a message: everything except its own messages.
pub(crate) fn add_given(allowed: &mut AllowedNumbers, message: &Value) {
    if message["role"] != "assistant" {
        allowed.add_json(&message["content"]);
    }
}

const SUMMARY: &str = "SELECT c.id, c.title, c.created_at, c.updated_at, COUNT(t.id), c.tools_version, COALESCE(SUM(LENGTH(t.transcript)), 0)
    FROM coach_conversations c LEFT JOIN coach_turns t ON t.conversation_id = c.id";

const TURN: &str = "SELECT id, conversation_id, seq, created_at, question, status, error_code, answer, provider, model, sent, unverified, usage
    FROM coach_turns";

fn get_summary(conn: &Connection, id: i64) -> Result<ConversationSummary> {
    conn.query_row(&format!("{SUMMARY} WHERE c.id = ?1 GROUP BY c.id"), [id], summary_row)
        .optional()?
        .ok_or_else(|| CoreError::NotFound(format!("conversation {id}")))
}

fn get_turn(conn: &Connection, id: i64) -> Result<CoachTurn> {
    Ok(conn.query_row(&format!("{TURN} WHERE id = ?1"), [id], turn_row)?)
}

fn summary_row(r: &rusqlite::Row) -> rusqlite::Result<ConversationSummary> {
    let turn_count: i64 = r.get(4)?;
    let tools_version: u32 = r.get(5)?;
    let bytes: i64 = r.get(6)?;
    Ok(ConversationSummary {
        id: r.get(0)?,
        title: r.get(1)?,
        created_at: r.get(2)?,
        updated_at: r.get(3)?,
        turn_count: turn_count as usize,
        read_only: tools_version != TOOLS_VERSION,
        full: turn_count as usize >= MAX_TURNS || bytes as usize >= MAX_HISTORY_BYTES,
    })
}

fn turn_row(r: &rusqlite::Row) -> rusqlite::Result<CoachTurn> {
    let status: String = r.get(5)?;
    let sent: String = r.get(10)?;
    let unverified: String = r.get(11)?;
    let usage: Option<String> = r.get(12)?;
    Ok(CoachTurn {
        id: r.get(0)?,
        conversation_id: r.get(1)?,
        seq: r.get(2)?,
        created_at: r.get(3)?,
        question: r.get(4)?,
        status: if status == "answered" { TurnStatus::Answered } else { TurnStatus::Failed },
        error_code: r.get(6)?,
        answer: r.get(7)?,
        provider: r.get(8)?,
        model: r.get(9)?,
        sent: serde_json::from_str(&sent).unwrap_or(Value::Null),
        unverified: serde_json::from_str(&unverified).unwrap_or_default(),
        usage: usage.and_then(|u| serde_json::from_str(&u).ok()),
    })
}
